# @package _group_

common:
  #fp16: false
  fp16: true
  # log_format: json
  log_format: simple
  log_interval: 20

checkpoint:
  no_epoch_checkpoints: true
  best_checkpoint_metric: loss

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: ltr
  autoregressive: true
  max_sample_size: 400000
  #max_sample_size: 800000

dataset:
  num_workers: 8
  max_tokens: 800000
  skip_invalid_size_inputs_valid_test: true
  train_subset: train
  valid_subset: valid
  validate_after_updates: 1000000
  validate_interval_updates: 2000
  # validate_interval: 100

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: cifencoder_loss
  zero_infinity: true

optimization:
  max_update: 80000
  lr: [5e-05]
  sentence_avg: false
  update_freq: [8]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
####   _name: tri_stage
####   phase_ratio: [0.1, 0.4, 0.5]
####   final_lr_scale: 0.05
  _name: tri_stage
  #warmup_steps: 8000
  #hold_steps: 52000
  #decay_steps: 40000
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_cifencoder
  w2v_path: ???
  encode_embed_dim: 768
  apply_mask: true
  mask_prob: 0.5
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  #freeze_finetune_updates: 10000
  ####freeze_finetune_updates: 8000
  freeze_finetune_updates: 0

